sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
  - "pypy"
  - "pypy3"
install: pip install .
script: py.test
notifications:
  email:
    recepients:
      - packwolf58@gmail.com
    on_success: never
    on_failure: always
