sudo: false
language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
install: pip install .
script: py.test -v tests
notifications:
  email:
    recepients:
      - packwolf58@gmail.com
    on_success: never
    on_failure: always
